#include<reg51.h>
#include<string.h>
#include"datatypes.h"
#include"register_names.h"
#include"initialization.h"
#include"delay.h"
#include"UART_Functionality.h"
#include"GSM_Functionality.h"
#include"Compare_Response.h"