extern void send(UINT8);
extern void uart_init(void);
extern UINT8 acknowledgement(void);
extern void start_communication(void);
extern void uart_transmit(void);
extern void uart_receive(void);
extern void gsm_ready(void);
//extern void send_message(char *);
extern void wait(void);
extern void receive_response(void);
extern void compare(void);
extern void delay();
extern void lcd_init();
extern void lcd_cmd(UINT8 cmd);
extern void lcd_data(UINT8 dat);
extern void lcd_disp(UINT8 disp);
